<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $communes = [
			['ALTO HOSPICIO', 1],
			['IQUIQUE', 1],
			['POZO ALMONTE', 1],
			['CAMIÑA', 1],
			['COLCHANE', 1],
			['HUARA', 1],
			['PICA', 1],
			['ANTOFAGASTA', 2],
			['MEJILLONES', 2],
			['SIERRA GORDA', 2],
			['TALTAL', 2],
			['CALAMA', 2],
			['OLLAGUAE', 2],
			['SAN PEDRO DE ATACAMA', 2],
			['TOCOPILLA', 2],
			['MARÍA ELENA', 2],
			['COPIAPÓ', 3],
			['CALDERA', 3],
			['TIERRA AMARILLA', 3],
			['CHAÑARAL', 3],
			['DIEGO DE ALMAGRO', 3],
			['VALLENAR', 3],
			['ALTO DEL CARMEN', 3],
			['FREIRINA', 3],
			['HUASCO', 3],
			['LA SERENA', 4],
			['COQUIMBO', 4],
			['ANDACOLLO', 4],
			['LA HIGUERA', 4],
			['PAIGUANO', 4],
			['VICUÑA', 4],
			['ILLAPEL', 4],
			['CANELA', 4],
			['LOS VILOS', 4],
			['SALAMANCA', 4],
			['OVALLE', 4],
			['COMBARBALÁ', 4],
			['MONTE PATRIA', 4],
			['PUNITAQUI', 4],
			['RÍO HURTADO', 4],
			['VALPARAISO', 5],
			['CASABLANCA', 5],
			['CONCÓN', 5],
			['JUAN FERNANDEZ', 5],
			['PUCHUNCAVÍ', 5],
			['QUINTERO', 5],
			['VIÑA DEL MAR', 5],
			['ISLA DE PASCUA', 5],
			['LOS ANDES', 5],
			['CALLE LARGA', 5],
			['RINCONADA', 5],
			['SAN ESTEBAN', 5],
			['LA LIGUA', 5],
			['CABILDO', 5],
			['PAPUDO', 5],
			['PETORCA', 5],
			['ZAPALLAR', 5],
			['QUILLOTA', 5],
			['CALERA', 5],
			['HIJUELAS', 5],
			['LA CRUZ', 5],
			['NOGALES', 5],
			['SAN ANTONIO', 5],
			['ALGARROBO', 5],
			['CARTAGENA', 5],
			['EL QUISCO', 5],
			['EL TABO', 5],
			['SANTO DOMINGO', 5],
			['SAN FELIPE', 5],
			['CATEMU', 5],
			['LLAILLAY', 5],
			['PANQUEHUE', 5],
			['PUTAENDO', 5],
			['SANTA MARÍA', 5],
			['QUILPUÉ', 5],
			['LIMACHE', 5],
			['OLMUÉ', 5],
			['VILLA ALEMANA', 5],
			['RANCAGUA', 6],
			['CODEGUA', 6],
			['COINCO', 6],
			['COLTAUCO', 6],
			['DOÑIHUE', 6],
			['GRANEROS', 6],
			['LAS CABRAS', 6],
			['MACHALÍ', 6],
			['MALLOA', 6],
			['MOSTAZAL', 6],
			['OLIVAR', 6],
			['PEUMO', 6],
			['PICHIDEGUA', 6],
			['QUINTA DE TILCOCO', 6],
			['RENGO', 6],
			['REQUÍNOA', 6],
			['SAN VICENTE', 6],
			['PICHILEMU', 6],
			['LA ESTRELLA', 6],
			['LITUECHE', 6],
			['MARCHIHUE', 6],
			['NAVIDAD', 6],
			['PAREDONES', 6],
			['SAN FERNANDO', 6],
			['CHÉPICA', 6],
			['CHIMBARONGO', 6],
			['LOLOL', 6],
			['NANCAGUA', 6],
			['PALMILLA', 6],
			['PERALILLO', 6],
			['PLACILLA', 6],
			['PUMANQUE', 6],
			['SANTA CRUZ', 6],
			['TALCA', 7],
			['CONSTITUCIÓN', 7],
			['CUREPTO', 7],
			['EMPEDRADO', 7],
			['MAULE', 7],
			['PELARCO', 7],
			['PENCAHUE', 7],
			['RIO CLARO', 7],
			['SAN CLEMENTE', 7],
			['SAN RAFAEL', 7],
			['CAUQUENES', 7],
			['CHANCO', 7],
			['PELLUHUE', 7],
			['CURICÓ', 7],
			['HUALAÑE', 7],
			['LICANTÉN', 7],
			['MOLINA', 7],
			['RAUCO', 7],
			['ROMERAL', 7],
			['SAGRADA FAMILIA', 7],
			['TENO', 7],
			['VICHUQUEN', 7],
			['LINARES', 7],
			['COLBÚN', 7],
			['LONGAVÍ', 7],
			['PARRAL', 7],
			['RETIRO', 7],
			['SAN JAVIER', 7],
			['VILLA ALEGRE', 7],
			['YERBAS BUENAS', 7],
			['CONCEPCIÓN', 8],
			['CORONEL', 8],
			['CHIGUAYANTE', 8],
			['FLORIDA', 8],
			['HUALQUI', 8],
			['LOTA', 8],
			['PENCO', 8],
			['SAN PEDRO DE LA PAZ', 8],
			['SANTA JUANA', 8],
			['TALCAHUANO', 8],
			['TOMÉ', 8],
			['HUALPÉN', 8],
			['LEBU', 8],
			['ARAUCO', 8],
			['CAÑETE', 8],
			['CONTULMO', 8],
			['CURANILAHUE', 8],
			['LOS ÁLAMOS', 8],
			['TIRÚA', 8],
			['LOS ANGELES', 8],
			['ANTUCO', 8],
			['CABRERO', 8],
			['LAJA', 8],
			['MULCHÉN', 8],
			['NACIMIENTO', 8],
			['NEGRETE', 8],
			['QUILACO', 8],
			['QUILLECO', 8],
			['SAN ROSENDO', 8],
			['SANTA BARBARA', 8],
			['TUCAPEL', 8],
			['YUMBEL', 8],
			['ALTO BIOBÍO', 8],
			['CHILLÁN VIEJO', 8],
			['TEMUCO', 9],
			['CARAHUE', 9],
			['CUNCO', 9],
			['CURARREHUE', 9],
			['FREIRE', 9],
			['GALVARINO', 9],
			['GORBEA', 9],
			['LAUTARO', 9],
			['LONCOCHE', 9],
			['MELIPEUCO', 9],
			['NUEVA IMPERIAL', 9],
			['PADRE LAS CASAS', 9],
			['PERQUENCO', 9],
			['PITRUFQUÉN', 9],
			['PUCÓN', 9],
			['SAAVEDRA', 9],
			['TEODORO SCHMIDT', 9],
			['TOLTÉN', 9],
			['VILCÚN', 9],
			['VILLARRICA', 9],
			['CHOLCHOL', 9],
			['ANGOL', 9],
			['COLLIPULLI', 9],
			['CURACAUTÍN', 9],
			['ERCILLA', 9],
			['LONQUIMAY', 9],
			['LOS SAUCES', 9],
			['LUMACO', 9],
			['PURÉN', 9],
			['RENAICO', 9],
			['TRAIGUÉN', 9],
			['VICTORIA', 9],
			['PUERTO MONTT', 10],
			['CALBUCO', 10],
			['COCHAMÓ', 10],
			['FRESIA', 10],
			['FRUTILLAR', 10],
			['LOS MUERMOS', 10],
			['LLANQUIHUE', 10],
			['MAULLÍN', 10],
			['PUERTO VARAS', 10],
			['CASTRO', 10],
			['ANCUD', 10],
			['CHONCHI', 10],
			['CURACO DE VÉLEZ', 10],
			['DALCAHUE', 10],
			['PUQUELDÓN', 10],
			['QUEILÉN', 10],
			['QUELLÓN', 10],
			['QUEMCHI', 10],
			['QUINCHAO', 10],
			['OSORNO', 10],
			['PUERTO OCTAY', 10],
			['PURRANQUE', 10],
			['PUYEHUE', 10],
			['RÍO NEGRO', 10],
			['SAN JUAN DE LA COSTA', 10],
			['SAN PABLO', 10],
			['CHAITÉN', 10],
			['FUTALEUFÚ', 10],
			['HUALAIHUÉ', 10],
			['PALENA', 10],
			['COIHAIQUE', 11],
			['LAGO VERDE', 11],
			['AISÉN', 11],
			['CISNES', 11],
			['GUAITECAS', 11],
			['COCHRANE', 11],
			['O’HIGGINS', 11],
			['TORTEL', 11],
			['CHILE CHICO', 11],
			['RÍO IBAÑEZ', 11],
			['PUNTA ARENAS', 12],
			['LAGUNA BLANCA', 12],
			['RÍO VERDE', 12],
			['SAN GREGORIO', 12],
			['CABO DE HORNOS', 12],
			['ANTÁRTICA', 12],
			['PORVENIR', 12],
			['PRIMAVERA', 12],
			['TIMAUKEL', 12],
			['NATALES', 12],
			['TORRES DEL PAINE', 12],
			['SANTIAGO', 13],
			['CERRILLOS', 13],
			['CERRO NAVIA', 13],
			['CONCHALÍ', 13],
			['EL BOSQUE', 13],
			['ESTACIÓN CENTRAL', 13],
			['HUECHURABA', 13],
			['INDEPENDENCIA', 13],
			['LA CISTERNA', 13],
			['LA FLORIDA', 13],
			['LA GRANJA', 13],
			['LA PINTANA', 13],
			['LA REINA', 13],
			['LAS CONDES', 13],
			['LO BARNECHEA', 13],
			['LO ESPEJO', 13],
			['LO PRADO', 13],
			['MACUL', 13],
			['MAIPÚ', 13],
			['ÑUÑOA', 13],
			['PEDRO AGUIRRE CERDA', 13],
			['PEÑALOLÉN', 13],
			['PROVIDENCIA', 13],
			['PUDAHUEL', 13],
			['QUILICURA', 13],
			['QUINTA NORMAL', 13],
			['RECOLETA', 13],
			['RENCA', 13],
			['SAN JOAQUÍN', 13],
			['SAN MIGUEL', 13],
			['SAN RAMÓN', 13],
			['VITACURA', 13],
			['PUENTE ALTO', 13],
			['PIRQUE', 13],
			['SAN JOSÉ DE MAIPO', 13],
			['COLINA', 13],
			['LAMPA', 13],
			['TILTIL', 13],
			['SAN BERNARDO', 13],
			['BUIN', 13],
			['CALERA DE TANGO', 13],
			['PAINE', 13],
			['MELIPILLA', 13],
			['ALHUÉ', 13],
			['CURACAVÍ', 13],
			['MARÍA PINTO', 13],
			['SAN PEDRO', 13],
			['TALAGANTE', 13],
			['EL MONTE', 13],
			['ISLA DE MAIPO', 13],
			['PADRE HURTADO', 13],
			['PEÑAFLOR', 13],
			['VALDIVIA', 14],
			['CORRAL', 14],
			['LANCO', 14],
			['LOS LAGOS', 14],
			['MÁNFIL', 14],
			['MARIQUINA', 14],
			['PAILLACO', 14],
			['PANGUIPULLI', 14],
			['LA UNION', 14],
			['FUTRONO', 14],
			['LAGO RANCO', 14],
			['RÍO BUENO', 14],
			['ARICA', 15],
			['CAMARONES', 15],
			['PUTRE', 15],
			['GENERAL LAGOS', 15],
			['EL CARMEN', 16],
			['NINHUE', 16],
			['ÑIQUÉN', 16],
			['PEMUCO', 16],
			['PINTO', 16],
			['PORTEZUELO', 16],
			['QUILLÓN', 16],
			['QUIRIHUE', 16],
			['RANQUIL', 16],
			['SAN CARLOS', 16],
			['SAN FABIAN', 16],
			['SAN IGNACIO', 16],
			['SAN NICOLAS', 16],
			['TREGUACO', 16],
			['YUNGAY', 16],
			['CHILLAN', 16],
			['BULNES', 16],
			['COBQUECURA', 16],
			['COELEMU', 16],
			['COIHUECO', 16],
		];

		foreach ($communes as $index =>$commune) {
			DB::table('communes')->insert([
				'id' => $index + 1,
				'region_id' => $commune[1],
				'name' => $commune[0],
			]);
		}
    }
}
